### ISSUE TITLE
create a Blog on ReactJs

### ISSUE THREAD

**Issue by SarthakDeshmukh13** [Google-DSC-DMCE/Heaven-for-NON-CODERS#1]
Include technicalities like uses, popular UI libraries, React Hooks, Axios Library, Props, React State Management, Redux  etc.

Do the necessary inclusions in React.md file

**Comment by SarthakDeshmukh13** [comment]
> @SarthakDeshmukh13 can you assign me this issue under hacktoberfest 2023??

Yes Sure Go ahead.

**Comment by Suhaani07** [comment]
@SarthakDeshmukh13 have opened up the PR. Kindly check it out

**Comment by SarthakDeshmukh13** [comment]
Good Job @Suhaani07
